### ISSUE TITLE
Ouzo sees "/" as "/index.php".

### ISSUE THREAD

**Issue by PleaseDontKillMe** [letsdrink/ouzo-app#17]
Ouzo app was setup at "public_html" directory on vipserv hosting service. 

routes.php:
Routes::get("/', "users#index');
Routes::get("/hello', "users#hello');

this throws a 500 Internal Error
No route rule found for HTTP method [GET] and URI [/index.php]

changing
routes.php to:
Routes::get("/index.php', "users#index');
Routes::get("/index.php/hello', "users#hello');

removes all prolems. Altough i think this is not desired at all.

**Comment by piotrooo** [comment]
mod_rewrite module is enabled?

**Comment by PleaseDontKillMe** [comment]
yep it is.

**Comment by bbankowski** [comment]
Can you paste your .htaccess file?

**Comment by PleaseDontKillMe** [comment]
It's identical to the one in your repo
https://github.com/letsdrink/ouzo-app/blob/master/.htaccess

**Comment by piotrooo** [comment]
Maybe document root in not set correctly.
Have you any logs?

**Comment by PleaseDontKillMe** [comment]
I don't know if this is relevant, but following your 5 Minute Tutorial, at point 

composer.phar create-project letsdrink/ouzo-app:1.4.0 myproject


i executed

composer.phar create-project letsdrink/ouzo-app:1.4.0 public_html/newproject/


because app folder is not directly in the root path (it's in the public_html folder).

**Comment by piotrooo** [comment]
So your `DocumentRoot` must be set to `public_html/newproject/`.

Can you paste your `config.php` file? The `prefix_system` value can be set incorrect:

```php
config['global']['prefix_system'] = '/ouzo-test';
```

**Comment by PleaseDontKillMe** [comment]
config['global']['prefix_system'] is currently set to empty string.

Should it be
config['global']['prefix_system'] = '/ouzo-test';
or
config['global']['prefix_system'] = '/public_html/ouzo-test';

?

**Comment by piotrooo** [comment]
If `DocumentRoot` is set to `public_html` set:

```php
$config['global']['prefix_system'] = '/public_html/newproject';
```

And address will be: `example.com/newproject`.

`newproject` is your app dir.

**Comment by PleaseDontKillMe** [comment]
We want the address to be "example.com/".

**Comment by piotrooo** [comment]
So set `DocumentRoot` to `public_html/newproject`.

**Comment by PleaseDontKillMe** [comment]
I'm afraid I do not know how to set DocumentRoot :<

**Comment by bbankowski** [comment]
You have to set prefix_system to /. Do not change RewriteBase.

Set up at your hosting service that your domain is pointing to my_project directory (in admin panel).
